# GET http://localhost:3000/user/1 HTTP/1.1

# POST http://localhost:3000/add_user HTTP/1.1
# content-type: application/json

# {
#     "user_name": "mimi",
#     "user_pwd": "1111",
#     "first_name": "Milan",
#     "last_name": "Millor",
#     "email": "mimi@gmail.com"
# }

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user1",
    "password": "efe159585"
}